# Generated by Django 5.1.7 on 2025-03-27 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='customer',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='bid',
            old_name='customer',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='customer',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='customer',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='customer',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='wallet',
            old_name='customer',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='address',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='vendor',
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
