# Generated by Django 5.1.7 on 2025-03-24 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='user',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='bid',
            old_name='user',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='user',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='user',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='wallet',
            old_name='user',
            new_name='customer',
        ),
        migrations.AddField(
            model_name='wallet',
            name='address',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
