# Generated by Django 5.1.7 on 2025-04-10 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_cart_added_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discount',
            old_name='description',
            new_name='name',
        ),
    ]
