# Generated by Django 5.1.7 on 2025-04-10 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_description_discount_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='max_redemptions',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='discount',
            name='redemptions',
            field=models.IntegerField(blank=0, default=0, null=True),
        ),
    ]
