# Generated by Django 5.1.7 on 2025-04-10 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_discount_max_redemptions_discount_redemptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='redemptions',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
