# Generated by Django 5.1.7 on 2025-04-10 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_discount_redemptions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='user',
            new_name='vendor',
        ),
    ]
