# Generated by Django 5.1.7 on 2025-04-11 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_rename_user_rating_vendor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='vendor',
            new_name='user',
        ),
    ]
