# Generated by Django 5.2 on 2025-04-19 05:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_useditem_remove_bid_item_bid_used_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='useditem',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='used_items', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
