# Generated by Django 5.2 on 2025-04-19 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_useditem_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='user',
            name='business_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
