# Generated by Django 5.2 on 2025-04-21 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_user_telegram_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='vendor_type',
            field=models.CharField(blank=True, choices=[('individual', 'Individual'), ('business', 'Business')], default='individual', max_length=10, null=True),
        ),
    ]
