# Generated by Django 5.2 on 2025-04-24 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_orderitem_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='items/'),
        ),
        migrations.AddField(
            model_name='useditem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='used-items/'),
        ),
    ]
